# permissions for end users to view ybclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ybcluster-viewer-role
rules:
- apiGroups:
  - yugabyte.com
  resources:
  - ybclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yugabyte.com
  resources:
  - ybclusters/status
  verbs:
  - get
